version: '3.9'
services:
  nest:
    build: .
    restart: always
    ports:
      - '5000:5000'
      - '9229:9229'
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      NODE_ENV: 'dev'
    command: yarn start:debug
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: bloggers_posts
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - ./mongo_init_script/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    
volumes:
  mongodata: